baseURL = 'https://rootc-jc.github.io/'
languageCode = 'en-us'
title = 'jayachandra'
theme = 'risotto'
author = 'Jayachandra'

# Sidebar: about/bio
[params.about]
title = "rootc-jc"
description = "My personal website!"

[params.theme]
palette="base16-dark"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/rootc-jc"

[[params.socialLinks]]
icon = "fa-brands fa-twitter"
title = "X"
url = "https://x.com/rootc_jc"

[[params.socialLinks]]
icon = "fa fa-file"
title = "Resume"
url = "https://drive.google.com/file/d/1QemX_ZhcIY-X65gaDwQNnp5TbDZoPSOg/view?usp=sharing"

sectionPagesMenu = "main"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "progress-reports-failed"
    name = "Progress Reports Archive"
    url = "/progress-reports-failed/"
    weight = 3
